{{
    config(
        database='DBT_INFOFISCUS_LANDING_DEV'
        
    )
}}

WITH CONTACTS as (
SELECT 
"ID","ISDELETED","MASTERRECORDID","NAME","TYPE",NULL AS "RECORDTYPEID",
"PARENTID","BILLINGSTREET","BILLINGCITY","BILLINGSTATE","BILLINGPOSTALCODE",
"BILLINGCOUNTRY",NULL AS "BILLINGSTATECODE",NULL AS "BILLINGCOUNTRYCODE","BILLINGLATITUDE",
"BILLINGLONGITUDE","BILLINGGEOCODEACCURACY","SHIPPINGSTREET","SHIPPINGCITY","SHIPPINGSTATE",
"SHIPPINGPOSTALCODE","SHIPPINGCOUNTRY",NULL AS "SHIPPINGSTATECODE",NULL AS "SHIPPINGCOUNTRYCODE",
"SHIPPINGLATITUDE","SHIPPINGLONGITUDE","SHIPPINGGEOCODEACCURACY","PHONE","FAX","WEBSITE","PHOTOURL",
"SIC","INDUSTRY","ANNUALREVENUE","NUMBEROFEMPLOYEES","OWNERSHIP","TICKERSYMBOL","DESCRIPTION","SITE",
"OWNERID","CREATEDDATE","CREATEDBYID","LASTMODIFIEDDATE","LASTMODIFIEDBYID","SYSTEMMODSTAMP",
"LASTACTIVITYDATE","LASTVIEWEDDATE","LASTREFERENCEDDATE",NULL AS "ISPARTNER",NULL AS "ISCUSTOMERPORTAL",
"JIGSAW","JIGSAWCOMPANYID","ACCOUNTSOURCE","SICDESC","DANDBCOMPANYID","OPERATINGHOURSID ID","ISDELETED",
"NAME","PARENTID",NULL AS "RECORDTYPEID","TYPE","STATUS","STARTDATE","ENDDATE","EXPECTEDREVENUE",
"BUDGETEDCOST","ACTUALCOST",NULL AS "CAMPAIGNIMAGEID","EXPECTEDRESPONSE","NUMBERSENT","ISACTIVE",
"DESCRIPTION","NUMBEROFLEADS","NUMBEROFCONVERTEDLEADS","NUMBEROFCONTACTS","NUMBEROFRESPONSES",
"NUMBEROFOPPORTUNITIES","NUMBEROFWONOPPORTUNITIES","AMOUNTALLOPPORTUNITIES","AMOUNTWONOPPORTUNITIES",
NULL AS "CURRENCYISOCODE","OWNERID",NULL AS "TENANTID","CREATEDDATE","CREATEDBYID","LASTMODIFIEDDATE",
"LASTMODIFIEDBYID","SYSTEMMODSTAMP","LASTACTIVITYDATE","LASTVIEWEDDATE","LASTREFERENCEDDATE",
"CAMPAIGNMEMBERRECORDTYPEID ID","ISDELETED","MASTERRECORDID","ACCOUNTID","LASTNAME","FIRSTNAME",
"SALUTATION","NAME","OTHERSTREET","OTHERCITY","OTHERSTATE","OTHERPOSTALCODE","OTHERCOUNTRY","OTHERLATITUDE",
"OTHERLONGITUDE","OTHERGEOCODEACCURACY","MAILINGSTREET","MAILINGCITY","MAILINGSTATE","MAILINGPOSTALCODE",
"MAILINGCOUNTRY","MAILINGLATITUDE","MAILINGLONGITUDE","MAILINGGEOCODEACCURACY","PHONE","FAX","MOBILEPHONE",
"HOMEPHONE","OTHERPHONE","ASSISTANTPHONE","REPORTSTOID","EMAIL","TITLE","DEPARTMENT","ASSISTANTNAME",
"LEADSOURCE","BIRTHDATE","DESCRIPTION","OWNERID","CREATEDDATE","CREATEDBYID","LASTMODIFIEDDATE",
"LASTMODIFIEDBYID","SYSTEMMODSTAMP","LASTACTIVITYDATE","LASTCUREQUESTDATE","LASTCUUPDATEDATE","LASTVIEWEDDATE",
"LASTREFERENCEDDATE","EMAILBOUNCEDREASON","EMAILBOUNCEDDATE","ISEMAILBOUNCED","PHOTOURL","JIGSAW",
"JIGSAWCONTACTID","CLEANSTATUS","INDIVIDUALID",
  CURRENT_TIMESTAMP AS INSERT_DT
,"ID" AS KEY_ID
FROM
{{source('Infofiscus','CONTACTS')}}
INNER JOIN DBT_INFOFISCUS_LANDING_DEV.CT_SALESFORCE.INFOFISCUS_CT
ON SRC_OBJECT ='CONTACTS' AND TGT_OBJECT = 'STG_CONTACTS' 
 WHERE LASTMODIFIEDDATE >= LAST_RUN_DATE
)

SELECT * FROM CONTACTS
            