{{
    config(
        database='DBT_INFOFISCUS_LANDING_DEV'
        
    )
}}

WITH OPPORTUNITIES as (
SELECT 
"ID",
"ISDELETED",
"ACCOUNTID",
"ISPRIVATE",
"NAME",
"DESCRIPTION",
"STAGENAME",
"AMOUNT",
"PROBABILITY",
"EXPECTEDREVENUE",
"TOTALOPPORTUNITYQUANTITY",
"CLOSEDATE",
"TYPE",
"NEXTSTEP",
"LEADSOURCE",
"ISCLOSED",
"ISWON",
"FORECASTCATEGORY",
"FORECASTCATEGORYNAME",
"CAMPAIGNID",
"HASOPPORTUNITYLINEITEM",
"PRICEBOOK2ID",
"OWNERID",
"CREATEDDATE",
"CREATEDBYID",
"LASTMODIFIEDDATE",
"LASTMODIFIEDBYID",
"SYSTEMMODSTAMP",
"LASTACTIVITYDATE",
"PUSHCOUNT",
"LASTSTAGECHANGEDATE",
"FISCALQUARTER",
"FISCALYEAR",
"FISCAL",
"CONTACTID",
"LASTVIEWEDDATE",
"LASTREFERENCEDDATE",
"HASOPENACTIVITY",
"HASOVERDUETASK",
"LASTAMOUNTCHANGEDHISTORYID",
"LASTCLOSEDATECHANGEDHISTORYID",
  CURRENT_TIMESTAMP AS INSERT_DT
,"ID" AS KEY_ID
FROM
{{source('Infofiscus','OPPORTUNITIES')}}
INNER JOIN DBT_INFOFISCUS_LANDING_DEV.CT_SALESFORCE.INFOFISCUS_CT
ON SRC_OBJECT ='OPPORTUNITIES' AND TGT_OBJECT = 'STG_OPPORTUNITIES' 
 WHERE LASTMODIFIEDDATE >= LAST_RUN_DATE
)

SELECT * FROM OPPORTUNITIES
            